spring:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        highlight_sql: true
        jdbc:
          batch_size: 1000

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console
